// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLinks.Web.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MyLinks.Web.Migrations
{
    [DbContext(typeof(MyLinksContext))]
    [Migration("20190402144452_dataseed")]
    partial class dataseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MyLinks.Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tech"
                        });
                });

            modelBuilder.Entity("MyLinks.Web.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoryId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Url = "http://uneurldetest.com"
                        });
                });

            modelBuilder.Entity("MyLinks.Web.Models.Link", b =>
                {
                    b.HasOne("MyLinks.Web.Models.Category", "Category")
                        .WithMany("Links")
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
